### PR TITLE
Change Entity Access

### PR DESCRIPTION
**Pull request by nskonieczko**
Chang access control of `Entity`

### CODE REVIEW

**Comment by ShadyGhalab** [comment]
@rizwankce @nysander Can we merge this one guys?

**Comment by nysander** [comment]
sorry for the delay, and thanks for your PR

**Comment by ShadyGhalab** [comment]
> sorry for the delay, and thanks for your PR

It wasn't my PR. Credits go to @nskonieczko. Thanks for merging it.

**Comment by MainasuK** [comment]
The SPM needs a new version tag to make it accessible. Could you please tag it something like `0.0.2`?

Thank you.

**Comment by nysander** [comment]
Sure

**Comment by nysander** [comment]
done

**Comment by MainasuK** [comment]
> done

Thanks a lot. 👍

**Pull request merged**
