### PR TITLE
Solved config files path and updated access control of ConfigurationType and Entity

### PR DESCRIPTION
**Pull request by Kyome22**
When I tried to use the library in my project, I faced the problem that I could not resolve the resource path of config's JSON files and could not access the properties that I could access before with the original twitter-text.

The main modifications are as follows.
- Changed the access control of the properties of the `Entity` class from `internal` to `public`.
- Changed the access control of the `ConfigurationType` enum from `internal` to `public`.
- Fixed to use ConfigurationType as enum correctly.
- Changed the location of the Config folder to use the Swift Package Manager's resource resolution feature.

I hope you will accept my pull request.

### CODE REVIEW

**Comment by nysander** [comment]
thank you for contribution. You have changed swift version. Please revert this to 5.2 and if not possible please provide good reason why we need to drop 5.2. Now CI tests  on linux are failing

**Comment by Kyome22** [comment]
@nysander 
Thank you for checking my pull request.

According to the reference from [Apple's document](https://developer.apple.com/documentation/swift_packages/bundling_resources_with_a_swift_package),
> If you declare a Swift tools version of 5.3 or later in your package manifest, you can bundle resources with your source code as Swift packages.

In other words, it seems that the version of swift-tools needs to be 5.3 or higher in order to solve this resource path problem.

**Comment by Kyome22** [comment]
@nysander Hi, I checked workflows in GitHub Actions. And I have one question. 
Why do you need the Linux workflow? 
I think Linux workflow not necessary because the test has already run on the macOS workflow.

**Comment by nysander** [comment]
linux workflow was required because this library is used by me on server side swift appliance running on Ubuntu host. macOS Foundation differs from open source version of Foundation library

**Comment by Kyome22** [comment]
@nysander 
I understood that Linux workflow is required. However, this CI has not passed since before my PR.
Also, it seems that the CI did not pass for #17 which was recently merged.
https://github.com/nysander/twitter-text/actions/runs/1899060717

What should I do?

**Comment by nysander** [comment]
Resolve conflicts and I will merge for now.

**Comment by Kyome22** [comment]
@nysander 
> Resolve conflicts and I will merge for now.

Thank you for replying. I resolved conflicts, please review.

**Comment by nysander** [comment]
Done thanks for your help. And sorry for such long time

**Pull request merged**
